---
name: Checks

# This is the trigger
on: [push]

jobs:
  test-lint:
    name: Test and Ling
    runs-on: ubuntu-20.04 # the operating system you will be running your jobs on
    steps:
      - name: Login to Docker Hub
        users: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # some jobs don't require the code to run the job
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"